rules:
  self-repository:
    # actionlint 1.7.12 does not understand $/ references yet
    # Remove these exceptions when https://github.com/rhysd/actionlint/issues/711
    # is released. All local actions run after an uncredentialed checkout
    ignore:
      - check.yaml
      - github-pages.yaml
      - nix-check.yaml
      - update-discord.yaml
      - update-plugins.yaml
