import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { union } from 'polyclip-ts';

type Point = [x: number, y: number];
type Polygon = Point[];

// Approved proportions. Distances are SVG units except the normalized lambda.
const logo = {
  size: 380,
  fill: '#5865f2',
  arms: { count: 6, radius: 180, thickness: 27 / 100, gap: 1 / 32 },
  core: { radius: 98, sides: 96 },
  corners: { trim: 17, maxEdgeFraction: 0.4 },
  eyes: { offsets: [-43, 43], y: -3, radiusX: 16, radiusY: 21 },
} as const;
const rendering = {
  decimalPlaces: 6,
  output: resolve(import.meta.dirname, '../public/nixcord-logo.svg'),
} as const;
const fullTurn = 2 * Math.PI;

const add = (a: Point, b: Point): Point => [a[0] + b[0], a[1] + b[1]];
const subtract = (a: Point, b: Point): Point => [a[0] - b[0], a[1] - b[1]];
const multiply = (p: Point, scale: number): Point => [p[0] * scale, p[1] * scale];
const at = (polygon: Polygon, index: number): Point =>
  polygon[(index + polygon.length) % polygon.length];
const format = (p: Point): string =>
  p.map((n) => Number(n.toFixed(rendering.decimalPlaces))).join(' ');

function rotate([x, y]: Point, angle: number): Point {
  return [x * Math.cos(angle) - y * Math.sin(angle), x * Math.sin(angle) + y * Math.cos(angle)];
}

// Adapted from NixOS's hexagonal lambda construction, artwork CC BY 4.0
// https://github.com/NixOS/branding
// https://brand.nixos.org/documents/nixos-branding-guide.pdf (pages 7–13)
// Changes: joined center, heavier arms, rounded boundary, and eye cutouts
const { thickness, gap, radius, count } = logo.arms;
const lambda: Polygon = [
  [-1 / 2 - thickness / 2 + gap, -1 + thickness + 2 * gap],
  [-1 / 2 + thickness / 2 + gap, -1 - thickness + 2 * gap],
  [1 / 2 + thickness, 1],
  [1 / 2 - thickness, 1],
  [0, 2 * thickness],
  [-1 / 2 + thickness, 1],
  [-1 / 2, 1],
  [-1 / 2 - thickness / 2, 1 - thickness],
  [-thickness, 0],
];
const scale = radius / (2 + thickness);
const arm: Polygon = lambda.map(([x, y]) => [
  scale * (x - 1 / 2 - thickness / 2),
  scale * (Math.sqrt(3) / 2) * (y + 1 + thickness),
]);
// Reuse the same angular sampling for the arms and regular center polygon
function angles(count: number): number[] {
  return Array.from({ length: count }, (_, i) => (i * fullTurn) / count);
}

const shapes: Polygon[] = [
  ...angles(count).map((angle) => arm.map((point) => rotate(point, angle))),
  angles(logo.core.sides).map((angle) => rotate([logo.core.radius, 0], angle)),
];

function outline(polygons: readonly Polygon[]): Polygon {
  const merged = union(polygons.map((polygon) => [polygon]));
  if (merged.length !== 1 || merged[0].length !== 1) {
    throw new Error('Logo must have one connected outline without holes');
  }
  // Union returns closed rings; rounding expects each vertex only once.
  return merged[0][0].slice(0, -1);
}

// Quadratic corner fillets, capped so adjacent trims cannot cross
function rounded(polygon: Polygon): string {
  return (
    polygon
      .map((point, i) => {
        const toward = (neighbor: Point): Point => {
          const vector = subtract(neighbor, point);
          return add(
            point,
            multiply(
              vector,
              Math.min(logo.corners.trim / Math.hypot(...vector), logo.corners.maxEdgeFraction)
            )
          );
        };
        return `${i ? 'L' : 'M'}${format(toward(at(polygon, i - 1)))}Q${format(point)} ${format(toward(at(polygon, i + 1)))}`;
      })
      .join('') + 'Z'
  );
}

// Even-odd filling cuts out the eyes without masks or document-global IDs
const eyes = logo.eyes.offsets
  .map((x) => {
    const { radiusX: rx, radiusY: ry, y } = logo.eyes;
    return `M${x - rx} ${y}a${rx} ${ry} 0 1 0 ${2 * rx} 0a${rx} ${ry} 0 1 0 ${-2 * rx} 0Z`;
  })
  .join('');
const viewBox = [-logo.size / 2, -logo.size / 2, logo.size, logo.size].join(' ');
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" role="img" aria-label="Nixcord">
  <title>Nixcord</title>
  <desc>Six rounded lambdas joined into a blue snowflake with two eye cutouts</desc>
  <!-- Generated by scripts/generate-nixcord-logo.ts -->
  <metadata>Adapted from NixOS artwork by the NixOS contributors, CC BY 4.0: https://github.com/NixOS/branding - https://creativecommons.org/licenses/by/4.0/</metadata>
  <path fill="${logo.fill}" fill-rule="evenodd" d="${rounded(outline(shapes))}${eyes}"/>
</svg>
`;
const { output } = rendering;
await mkdir(dirname(output), { recursive: true });
await writeFile(output, svg);
